<?php

/*
Implements hook_menu
*/
function rip_custom_pages_menu() {
	$items['inicio'] = array(
		'title' => 'Início',
		'description' => t('O maior e mais antigo fã-site Brasileiro sobre o Megadeth!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['noticias'] = array(
		'title' => 'Notícias',
		'description' => t('Notícias e todas as novidades relacionadas ao Megadeth!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['megadeth/agenda'] = array(
		'title' => 'Agenda',
		'description' => t('Confira toda a agenda da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['megadeth/biografia'] = array(
		'title' => 'Biografia',
		'description' => t('Confira a biografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	/*$items['megadeth/formacoes'] = array(
		'title' => 'Formações',
		'description' => t('Confira informações sobre todas as formações da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);*/

	$items['megadeth/integrantes'] = array(
		'title' => 'Integrantes',
		'description' => t('Confira informações sobre todos os integrantes da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['curiosidades'] = array(
		'title' => 'Curiosidades',
		'description' => t('Confira curiosidades sobre a banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/albuns-de-estudio'] = array(
		'title' => 'Álbuns de Estúdio',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/albuns-ao-vivo'] = array(
		'title' => 'Álbuns ao Vivo',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/videografia'] = array(
		'title' => 'Videografia',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/coletaneas'] = array(
		'title' => 'Coletâneas',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/singles'] = array(
		'title' => 'Singles',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/eps'] = array(
		'title' => 'EPs',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/bootlegs'] = array(
		'title' => 'Bootlegs',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/trilhas-sonoras'] = array(
		'title' => 'Trilhas Sonoras',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['discografia/outros'] = array(
		'title' => 'Outros',
		'description' => t('Confira informações sobre a discografia da banda!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['materias'] = array(
		'title' => 'Matérias',
		'description' => t('Confira matérias, reviews e opiniões sobre os mais variados assuntos relacionados ao Megadeth!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['rust-in-page'] = array(
		'title' => 'Matérias',
		'description' => t('Saiba mais sobre a equipe que trabalha dentro da Rust In Page!'),
		'page callback' => 'rip_home',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	return $items;
}

function rip_home() {
	return "";
}


?>